/*

Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.
*/
import java.util.Scanner;
public class Problem_2 {
	
	public static void main(String[] args) {

		int p1 = 1; //previous term
		int p2 = 0; //term previous to p1
		int term = 0;
		long evenSum = 0;

		while(term < 4000000) {

			term = p2 + p1;
			p2 = p1;
			p1 = term;

			if((term % 2) == 0) {
				evenSum = evenSum + term;
			}
		}
		System.out.println(evenSum);
	}
}